autodock_node:
  ros__parameters:
    target_tag_id: 0
    tag_family: "tag36h11"
    tag_frame_override: ""     
    base_frame: "base_link"

    final_stop_distance: 0.90


    align_radius: 1.20

    stop_distance_tolerance: 0.03
    final_heading_tolerance: 0.05

    approach_linear_speed: 0.25
    final_approach_linear_speed: 0.08
    max_angular_speed: 0.6
    kp_heading: 1.5
    kp_final_heading: 1.2   
    kp_linear: 0.6


    tag_normal_sign: 1.0


    normal_filter_alpha: 0.25
    normal_ambiguity_dot_threshold: 0.0


    camera_forward_x: 1.0
    camera_forward_y: 0.0

    tag_lost_timeout: 1.0
    search_rotate_speed: 0.3
    search_timeout: 20.0
    max_search_reattempts: 3

    enable_blind_final_creep: true
    blind_creep_speed: 0.05
    blind_creep_duration: 1.0
    blind_creep_trigger_distance: 0.15

    control_period: 0.05
    cmd_vel_topic: "cmd_vel"
    status_topic: "autodock/status"
